### ISSUE TITLE
Push me. 📌 

### ISSUE THREAD

**Issue by ABHAY0O7** [opencodeiiita/GoGit#10]
Create a directory inside `CONTRIBUTORS` of any name. 
Now add, commit and push your changes to the repo.
So simple, just do that.
⌚ 
⌚ 
But in doing so you will face a problem.
`I want that problem (you faced above) and the reason for that problem i.e. why you are facing that problem` inside your `info.md` file.
Now add, commit and push your changes by following the contributions guidelines.

**Comment by ashutosh3027** [comment]
https://github.com/opencodeiiita/Collaborative-Web.git

**Comment by ashutosh3027** [comment]
claim

**Comment by hardikarora2** [comment]
claim

**Comment by The-Divyansh** [comment]
claim

**Comment by bipulkmr-crypto** [comment]
claim

**Comment by naman-cr** [comment]
claim

**Comment by A-Spiral-Forge** [comment]
claim

**Comment by VineethKumarM** [comment]
Claim

**Comment by Palak-2109** [comment]
claim

**Comment by underoot-iota** [comment]
Claim

**Comment by anshumanjain2010** [comment]
claim

**Comment by 99anjali** [comment]
claim

**Comment by the-grignard-reagent** [comment]
claim

**Comment by ABHAY0O7** [comment]
@ashutosh3027, you can work on this issue.

**Comment by Archit2002** [comment]
claim

**Comment by Mantraraj8472** [comment]
Claim

**Comment by codelord09** [comment]
claim

**Comment by aastha01chauhan** [comment]
claim, I want to work on this!

**Comment by J-e-e-t** [comment]
claim

**Comment by Nikita9344** [comment]
claim

**Comment by aviralgupta752** [comment]
claim

**Comment by Pranav-22-aditya** [comment]
claim

**Comment by canaryGrapher** [comment]
claim

**Comment by Aman-IIITA** [comment]
claim

**Comment by souvenger** [comment]
claim

**Comment by ArshpreetS** [comment]
claim

**Comment by the-grignard-reagent** [comment]
claim

**Comment by the-grignard-reagent** [comment]
claim

**Comment by ArshpreetS** [comment]
claim

**Comment by ABHAY0O7** [comment]
This issue was successfully solved by @ashutosh3027  in #92
