### ISSUE TITLE
Update gitignore

### ISSUE THREAD

**Issue by ABHAY0O7** [opencodeiiita/GoGit#127]
`If your `info.md` file doesn't exist on this repo, then read the second point of` [CONTRIBUTING.md](https://github.com/opencodeiiita/GoGit/blob/main/CONTRIBUTING.md) `and create your info.md file and then push it and make a PR without mentioning any issue number in the description. Now, wait for the merge of that PR and after merging proceed with this task.`

**Task starts from here ------------------------------------------------------------------------------------------------------------------**

Add your `info.md` file inside gitignore.
Then push your changes and make a PR.

**It is mandatory to make a PR for the above changes before moving to the next part of the task. Also, mention the issue number in this PR.**

After this, you need to make one more commit such that after pushing that commit, your info.md file should exist on your local system, but not in your PR's `files changed` section.
`Files changed` section should have something like this for your info.md file.
![image](https://user-images.githubusercontent.com/75938293/136280145-c430afd9-5849-4068-8a56-2deada10ac39.png)

### Conditions that must be followed by you:-
- You can't delete your info.md file by just performing any deletion operation in your system like you just can't do left-click and then delete.
- You can't cut that file and paste it into any other directory.
- You can't use any git or terminal commands that delete your `info.md` file from your system.
- Only two commits are allowed for the PR, lesser and greater can lead to closed PR.
- No need to write any git commands in the PR message just write the issue number and some appropriate description.

## Important message:- When you start working on this task, please write every git command that you used to do this task in a notepad or your notebook or anywhere else you like. 
***When I will be finally reviewing your PR, at that time I will call you on the GoGit voice channel of discord to check that whether you did this task in a fair way or not i.e. whether the file exists in your directory or not and for the git commands too.***
So please, be active on discord after completing your PR.

**Comment by Abhijeet452** [comment]
@ABHAY0O7 do we need to wait for the merge of that PR which we have created after adding info.md file in .gitignore?

**Comment by ABHAY0O7** [comment]
### Everyone, after making your PR with two commits, if there are any merge conflicts then don't solve them until I told you to do that. Just leave the PR as it is for review.
