### ISSUE TITLE
Merge it.

### ISSUE THREAD

**Issue by ABHAY0O7** [opencodeiiita/GoGit#224]
### This task must be completed before any PR got merged for issue #223 i.e. one who claims it must complete this task before 1:00 PM today.

First, you have to answer a question in your info.md file and make a commit **on `branch-1`**. (See that this branch already exists on this repo so no need to create a new one). After this, you have to merge `branch-1` into `main` and then make a PR with your main branch.

**Ques -** Above, I told you to merge branch-1 into main, tell me which type of merge is this and why? Also, explain it too.

#### Important points:
- Before making PR, there should be only two commits in your PR, one done by me and one by you.
- If you make more than one commit, then no problem, you can squash your commits into one, but you can't squash my commit, i.e. my commit should be as it is.
- The commit done by you should have both a title and a description.
- If you are the first to claim this issue, then don't wait for my reply, assume that it is assigned to you and you have to complete it before the deadline.
- No extra time will be given for correction, so try to do it in a single attempt.

**Comment by Ksathwik03** [comment]
Unassigned??

**Comment by ABHAY0O7** [comment]
This task was successfully solved by @Ksathwik03 in #235
