### ISSUE TITLE
Different delete. 

### ISSUE THREAD

**Issue by ABHAY0O7** [opencodeiiita/GoGit#366]
`Task: You have to make two commits, then push them and make a PR. And after this, you have to delete any one commit and then again you have to push your changes. After this push just tag me in your next reply and also mention all the used git commands correctly and in a proper way.`

Now before making those first two commits, you have to decide that which commit you are gonna delete later. Suppose you decided that you will be deleting the first commit so answer the question in your second commit and in the first commit you can do whatever you want at your convenience because finally, it is going to vanish. 
**Ques -** Explain the whole process that you will be using to delete that commit.

### Now, the twist is that you can't use the same process that is already merged i.e. if someone did the task successfully with a unique process then after him, no one can use that same process to delete the commit.
- If two PRs have the same process then, the one who did it first and correctly will be merged and after this, the other contributor has to use a different method.
- Any numbers of PRs **(open or closed)** are acceptable, but the condition is that you can't delete your repo. 
- In the end, your PR must have only one commit.

Don't forget to tag me in the end. Also, tag only one time, cause it will be beneficial to you.
This is an everyone issue, so if your PR has a unique method of removing a commit, then I will merge your PR.
Currently no deadline for the issue.

PS: If you want to do this task by any easy method, then do it first. 🙈

**Comment by Ksathwik03** [comment]
Claik
