### ISSUE TITLE
First time contributors.

### ISSUE THREAD

**Issue by ABHAY0O7** [opencodeiiita/GoGit#4]
## This issue is constrained only to those who never contributed over GitHub.

- First fork this repo and then clone it to your local system.
- Now go over GitHub and create a new personal repository (Public) by yourself of any name and description and copy its URL.
- Add your `info.md` file to this repo as I mentioned in the [CONTRIBUTING.md](https://github.com/opencodeiiita/GoGit/blob/main/CONTRIBUTING.md)
- Also add the repo URL that you created above in your info file.
- Now add, commit and push your code and then open a PR.

For your help, all the resources are available on the `Go-git` and `git-and-github` channel of our Discord server.

**Comment by karankc23** [comment]
Claim, I want to work on this issue,

**Comment by A-Spiral-Forge** [comment]
Please assign this issue to me

**Comment by adtoria** [comment]
Claim

**Comment by medhatiwari** [comment]
Please assign me this issue!

**Comment by 99anjali** [comment]
claim

**Comment by 0Rituraj01** [comment]
hey Abhay, i want to work on this issue

**Comment by Palak-2109** [comment]
claim

**Comment by shadaanhussain** [comment]
I want this issue. Please assign it to me.

**Comment by anu-phoenix** [comment]
claim

**Comment by Yash091** [comment]
claim

**Comment by gudelakshmi** [comment]
claim

**Comment by naman-cr** [comment]
claim

**Comment by jalanprakhar** [comment]
claim

**Comment by AshuZ-dot** [comment]
claim

**Comment by Prajit-Sengupta** [comment]
interested

**Comment by J-e-e-t** [comment]
claim

**Comment by Nikita9344** [comment]
claim

**Comment by bipulkmr-crypto** [comment]
claim

**Comment by bipulkmr-crypto** [comment]
claim

**Comment by raghavgoel25** [comment]
claim

**Comment by naman-cr** [comment]
claim

**Comment by Pranav-22-aditya** [comment]
claim

**Comment by Naman-11** [comment]
claim, i want to work on this issue

**Comment by saloni33** [comment]
claim

**Comment by rushilpatra** [comment]
claim

**Comment by raman5911** [comment]
Claim, I want to work on this issue,

**Comment by ABHAY0O7** [comment]
So, it seems that none of you has read the task before claiming it. 😅 
Don;t worry, this time I am distinguishing the contributors, but from next time I will suggest pro devs to not to claim only for beginner issues.
Okay! this issue is open for every beginner, so only those who are on this list can work on this issue.
- @0Rituraj01 
- @Palak-2109 
- @shadaanhussain 
- @anu-phoenix 
- @naman-cr 
- @AshuZ-dot 

You can start working on this issue.
And don;t be sad, I will reply to this thread with some more names soon.

**Comment by ArshpreetS** [comment]
Claim, I want to work on this issue

**Comment by ABHAY0O7** [comment]
- @bipulkmr-crypto 
- @raghavgoel25 
- @Pranav-22-aditya 
- @Naman11
- @rushilpatra
 You guys can also work on this issue.

**Comment by underoot-iota** [comment]
Claim, I want to work on this issue.

**Comment by aastha01chauhan** [comment]
claim, I want to work on this.

**Comment by AmbikeshArman** [comment]
claim

**Comment by ABHAY0O7** [comment]
Those who didn't get the claim for this issue, don't worry, I will be releasing some more issues in some minutes.

**Comment by codesanta142** [comment]
claim

**Comment by 99anjali** [comment]
please assign to me

**Comment by Mantraraj8472** [comment]
Claim

**Comment by Archit2002** [comment]
Claim

**Comment by Perry0107** [comment]
claim

**Comment by ashutosh3027** [comment]
claim

**Comment by vemulapandu** [comment]
claim

**Comment by ABHAY0O7** [comment]
- @aastha01chauhan 
- @underoot-iota 
- @AmbikeshArman 
- @the-grignard-reagent 
- @Mantraraj8472 
- @Archit2002
- @Perry0107 

You guys can also work on this issue.

**Comment by ABHAY0O7** [comment]
Ok guys, we have decided that everyone who claimed above, can work on this issue, all will get equal points. 😄

**Comment by Abhijeet452** [comment]
Claim

**Comment by gaurav1058** [comment]
claim

**Comment by vipulranjansahu** [comment]
claim

**Comment by Sakshi2020037** [comment]
claim

**Comment by VineethKumarM** [comment]
claim

**Comment by Aman-IIITA** [comment]
Claim, Abhay sir pls assign this to me.

**Comment by taniya-27** [comment]
Pls claim!

**Comment by isharawat** [comment]
claim

**Comment by ABHAY0O7** [comment]
Anyone who claims this issue can do it, you don't need to wait for the assignee label, just make a PR that follows the PR template.
For PR help see [this ](https://github.com/opencodeiiita/GoGit/pull/5#issuecomment-933009896)

**Comment by janhaviiii** [comment]
claim

**Comment by hotblooded058** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by Kavita-Dhamot** [comment]
claim

**Comment by krypton001** [comment]
claim

**Comment by rajpranav63** [comment]
claim

**Comment by shlesh** [comment]
claim

**Comment by codelord09** [comment]
Please assign this issue to me

**Comment by Pratyush7901** [comment]
claim

**Comment by ABHAY0O7** [comment]
Anyone who claims this issue can do it, you don't need to wait for the assignee label, just make a PR that follows the PR template.

**Comment by prxtikk-18** [comment]
Claim

**Comment by J-e-e-t** [comment]
claim

**Comment by gudelakshmi** [comment]
claim

**Comment by Ayushi181** [comment]
claim

**Comment by Rishabh0612** [comment]
claim

**Comment by Puja-Saraf** [comment]
claim

**Comment by aashitachouhan** [comment]
claim

**Comment by AKI35429** [comment]
claim

**Comment by Shubhi2002** [comment]
claim

**Comment by anupamraj2001** [comment]
claim, i want to work on it.

**Comment by Harshgupta5901** [comment]
claim

**Comment by Harshgupta5901** [comment]
#79

**Comment by ABHAY0O7** [comment]
This issue will be closed at 12:00 PM today. No new PRs will be accepted after that.

**Comment by MUKILAN-2003** [comment]
Claim

**Comment by MUKILAN-2003** [comment]
Claim, I want to work on this issue

**Comment by ABHAY0O7** [comment]
Ok, I will accept new PRs for this issue up to 00:00 AM today.
But the condition is that the PR must be completely correct. If there will be an error in your PR or your PR message then I will close it and no further PRs will be allowed from you for this issue.

**Comment by ABHAY0O7** [comment]
This issue is no longer accepting any PRs

**Comment by andrebotin** [comment]
Claim
