### ISSUE TITLE
Merge your PRs

### ISSUE THREAD

**Issue by ABHAY0O7** [opencodeiiita/GoGit#437]
First, create a new branch with the name `main-copy`, and after creating this, create 4 more new branches of any name.

**Note:** Remember all these 5 branches will help you in testing while performing this task. Don't create any PR on my repo with any of these branches.

In this task, you will learn how to merge PRs on your repo. 😃 

When someone creates a PR on your repo, then there are 4 ways (in my knowledge) to merge it into your repo, all these 4 methods are present in this image.
![image](https://user-images.githubusercontent.com/75938293/138582170-d0c4e8af-c9c7-43d3-8617-d5f09624eb0c.png)

Now other than `main-copy` you have 4 branches, so you create 4 PR from these branches to `main-copy` on your repo with any changes and commits you want and then merge all these 4 PRs with 4 different methods of the merge. While doing this, try to learn about how things work when we perform a particular kind of merge or why it is different from others, etc.

After doing all this testing stuff, now answer this question in your `info.md` and make a PR on my repo. 
**Ques -** Explain all these 4 different kinds of merge that you performed above and how a particular method is different from the others. What are the pros and cons of a particular method and some other similar things? In short, you have to differentiate all these 4 different kinds of methods. Also, tell that in general out of these 4 methods, which one is best and why?

You have to write this answer in your words only, and try to write it in a proper and good manner. 🙏🏽 

- Only one commit is allowed in the PR.
- Other than this answer, no any other changes should be present in your PR.
- Only one PR is allowed.
- Finally, in the end, provide links to all the 4 different merged PRs that you used for testing in the PR message.
- The title of your 4 test PRs should be the merge that you performed with that particular PR.

PS: If you didn't find the 4th method in the image, then don't ask me, try to find it yourself. 👍🏽

**Comment by KIRTEE-TECH** [comment]
When is the deadline for this issue.. .?
