### ISSUE TITLE
Add some workflows

### ISSUE THREAD

**Issue by ABHAY0O7** [opencodeiiita/GoGit#496]
I assume that until now you all know about one of our OpenCode projects `Numismatics`, and if you don't, visit it.
Now, you will see that currently, it has no GitHub workflows, so it is very hard for the mentor to test the contributor's code.
So now, you guys have to help him by creating a workflow.
Now visit my [numismatics](https://github.com/ABHAY0O7/Numismatics), and you will see that there is a GitHub workflow file present on the repo named `build.yaml`.
Currently, I only provided just the name of the workflow, but I want you to add some actions to it that could really help the mentor of `Numismatics`.

What needed to be done:-
- You have to add the Gradle build to the workflows so that we can check your code with build success or failures.
- Workflow must trigger on every push, PR, and `published release' on the main branch only.
- Workflow should run for all the latest versions of Windows and ubuntu.
- If possible, you can also cache the Gradle packages to speed up the further builds.
- Configure the Java 15 version before build i.e. build should run with java-15.
- You must use the matrix for OS selection. (Didn't understand this point? Read the documentation, you will get it.)

### For testing, you can use your own Numismatics, i.e. you just do some changes in the `build.yaml` so that workflows got triggered on every push, and you can see it running in the Actions tab near the Code tab on your GitHub repo. 

When your workflow successfully passes the Gradle build fulfilling all the conditions that I provided above and you think that you have done this correctly, you just squash all the commits that you did until now into one and will make a PR on my Numismatics. After this, I will verify your PR and if it got merged then you are done.
Now, in the end, you have to complete this formality too. 
You will make a PR on my GoGit answering this question.
**Ques -** What does dependabot do. Answer this in detail.

Anyone can do this task, but the points will be awarded to only one contributor who will do this first, i.e. the first PR that will get merged on my Numismatics will receive the points. Also, tag me after every change you do in your PR. 
PR reviewing will be done according to time, so ping only once in the PR after every update.

I am always there to help you on Discord, but first I will advise you to visit the [documentation](https://docs.github.com/en/actions).
If you didn't understand the task then just ping me on discord.
If you have any problems with completing the task ping me on discord.

**Comment by shlesh** [comment]
claim?🥺
