### ISSUE TITLE
Delete it!

### ISSUE THREAD

**Issue by ABHAY0O7** [opencodeiiita/GoGit#6]
Create a text file inside your name directory and write inside it that what will you do if you won OC.
Now add and commit and push your changes and make a PR.
After making the PR, do this :
Delete the following directories/files from this repo.

- Delete the `DeleteIt` directory inside contributors.
- Delete the `UCan'tDeleteMe.txt` file inside contributors.
- Delete the file that you recently pushed.

Now push all your changes to that same PR.

Remember, after merging your PR, any of the above-listed files should not exist on this repo. Failed to do so, may result in accepted but unpointed (you will not receive any points) PR.

**Comment by Aneesh02** [comment]
claim

**Comment by Perry0107** [comment]
claim

**Comment by codesanta142** [comment]
claim

**Comment by vipulranjansahu** [comment]
claim

**Comment by Archit2002** [comment]
claim

**Comment by Pranav-22-aditya** [comment]
claim

**Comment by Mantraraj8472** [comment]
Claim

**Comment by Perry0107** [comment]
claim

**Comment by gaurav1058** [comment]
claim

**Comment by ABHAY0O7** [comment]
@Aneesh02, go for it. You have 48 hours to complete it.

**Comment by Aneesh02** [comment]
@ABHAY0O7 Thanks!

**Comment by 99anjali** [comment]
claim

**Comment by adtoria** [comment]
Claim

**Comment by naman-cr** [comment]
claim

**Comment by Nikita9344** [comment]
claim

**Comment by bipulkmr-crypto** [comment]
claim

**Comment by Aman-IIITA** [comment]
Claim

**Comment by kumarpradumn** [comment]
claim

**Comment by Naman-11** [comment]
claim

**Comment by codelord09** [comment]
claim

**Comment by aastha01chauhan** [comment]
claim, I want to work on this!

**Comment by canaryGrapher** [comment]
claim

**Comment by souvenger** [comment]
claim

**Comment by ABHAY0O7** [comment]
This issue was successfully solved by @Aneesh02 in #112
