### ISSUE TITLE
Create a branch.

### ISSUE THREAD

**Issue by ABHAY0O7** [opencodeiiita/GoGit#8]
Create a new branch from the initial commit of this repo and name it as `initial-branch`.
Then answer the following question in your info.md` file.

**Ques - ** You will see that some repo on GitHub has a `main` branch as their main but some have a `master` branch as their main branch. So, please explain in which case Git/GitHub creates `main` as the main branch and in which case it creates `master` as the main branch.

Now add and commit your answer to this question and create a PR from this initial branch to this repo's `dummy-branch`.
Condition: You must use the SHA key of the initial commit in any one of the git commands that you will use to complete this task.
PR which will be unable to fulfill the condition can be rejected.
If your `info.md` file is not there, then you have to make a new one.

**Comment by Ksathwik03** [comment]
Claim

**Comment by medhatiwari** [comment]
Is it for everyone?

**Comment by codesanta142** [comment]
claim

**Comment by ABHAY0O7** [comment]
@Ksathwik03, go for it.

**Comment by karankc23** [comment]
claim

**Comment by vipulranjansahu** [comment]
claim

**Comment by Pratik-Sarkate** [comment]
claim

**Comment by gaurav1058** [comment]
claim

**Comment by ABHAY0O7** [comment]
Only those issues which are labeled with the `everyone` tag are open for all.
If @Ksathwik03 didn't solve this issue in nxt 48 hours, then this issue will be assigned to next claimer.

**Comment by adtoria** [comment]
Claim

**Comment by Perry0107** [comment]
claim

**Comment by naman-cr** [comment]
claim

**Comment by Mantraraj8472** [comment]
Claim

**Comment by Pranav-22-aditya** [comment]
claim

**Comment by 99anjali** [comment]
claim

**Comment by Archit2002** [comment]
Claim

**Comment by Nikita9344** [comment]
claim

**Comment by aastha01chauhan** [comment]
claim, I want to work on this!

**Comment by canaryGrapher** [comment]
claim

**Comment by Aman-IIITA** [comment]
claim

**Comment by souvenger** [comment]
claim

**Comment by ArshpreetS** [comment]
claim

**Comment by the-grignard-reagent** [comment]
claim
