### ISSUE TITLE
Find and add.

### ISSUE THREAD

**Issue by ABHAY0O7** [opencodeiiita/GoGit#87]
"I am a basic git related file which is present in almost all the repositories over GitHub but not present on this repo"
Guess the file "I" in the above phrase and add it to this repo.

First, find this file then I will tell you the further steps of this task.
The deadline to make a correct PR for this half of task is 1 PM today.

**Comment by ashutosh3027** [comment]
claim

**Comment by kaneki-ken260** [comment]
claim

**Comment by raghavgoel25** [comment]
claim

**Comment by Darkknight131714** [comment]
claim

**Comment by isharawat** [comment]
claim

**Comment by aviralgupta752** [comment]
claim

**Comment by ABHAY0O7** [comment]
Sorry @ashutosh3027, you are already working on two issues from this repo.
So @kaneki-ken260 Go for it. 👍🏽 
And also, the deadline to find the file is only 12 hours from now.
i.e you must make a PR that completes one half of this task before 1:00 PM today.
ATB

**Comment by ashutosh3027** [comment]
@ABHAY0O7  i am working on only one issue. So, I think  I am eligible for this issue

**Comment by ABHAY0O7** [comment]
> @ABHAY0O7 i am working on only one issue. So, I think I am eligible for this issue

You are working on one issue, but also your PR for issue #4 is still open, it means task1 is still incomplete.
So, I cannot assign you this task. Please give chance to others too. 🙏🏽

**Comment by ashutosh3027** [comment]
Thanks for clarifying 🙏.I thought the first issue is open for all so it will not count in assigned issues.

**Comment by codelord09** [comment]
claim

**Comment by aastha01chauhan** [comment]
claim

**Comment by Aman-IIITA** [comment]
Claim

**Comment by ABHAY0O7** [comment]
This issue was successfully solved by @kaneki-ken260 in #89
